### ISSUE TITLE
The file "objReleaseandroidinpackaged_resources" does not exist

### ISSUE THREAD

**Issue by joevotto** [DotNetToscana/See4Me#5]
I go to build the solution and it keeps telling me that The file "objReleaseandroidinpackaged_resources" does not exist. I am unsure what to do to get that to be generated.

**Comment by marcominerva** [comment]
Can you send us a screenshot of the error?

**Comment by joevotto** [comment]
I was able to resolve this issue by removing build tools 24 as described on this link for future reference: https://forums.xamarin.com/discussion/63356/the-file-obj-debug-android-bin-packaged-resources-does-not-exist
