### ISSUE TITLE
Identify Person's Name from Real Time Video.

### ISSUE THREAD

**Issue by RaviTeza31** [DotNetToscana/See4Me#9]
HI @marcominerva 

We trying to identify the person's name from real time video through web cam. for this we are unable to do so, because the person groups are not trained. we tried to train the person groups but we are failing there. 
find the link where we are trying to train the faces of persons
https://westus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/563879b61984550f30395236

Could you please give any suggestions that,
1. How to upload the person's image to train their faces in Face API.
2. Any other Repo for person face recognition from a real time video through web cam.

Your help would be great full to us, Thanks in advance.

Thanks and Regards
Ravi.

**Comment by marcominerva** [comment]
Hi!

Take a look to this documentation page: https://docs.microsoft.com/en-us/azure/cognitive-services/face/face-api-how-to-topics/howtoidentifyfacesinimage
